spring:
  h2:
    console:
      enabled: true
    port: 9093
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb2
      driver-class-name: org.h2.Driver
      username: sa
      password: