spring:
  h2:
    console:
      enabled: true
    port: 9092
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
